### ISSUE TITLE
我试了下，只能出现一列，没有两列

### ISSUE THREAD

**Issue by giscjj** [MeFelixWang/me-waterfall#1]
难道是我用的不对吗

**Comment by MeFelixWang** [comment]
请贴出相关代码或复现链接，以供排查

**Comment by MeFelixWang** [comment]
请贴出相关代码或复现链接，以供排查 @giscjj

**Comment by MeFelixWang** [comment]
@giscjj 经排查，因 npm 包名导致默认获取容器尺寸的逻辑失败（传入`width`方式不受影响），已发布新版解决此问题
