### ISSUE TITLE
当只有两个元素时，如果最后一个元素高度比第一个元素低，第一个元素会被切割掉。

### ISSUE THREAD

**Issue by guooni** [MeFelixWang/me-waterfall#3]
您好，感谢您做的这个库，非常实用。
我在使用的过程中，发现如题所示的 BUG，我看了源码但是没法解决，您可以看看吗？
复现过程：
1. 正常展示一个列表。
2. 变更成只有两个数据的列表。
3. 调用 reflow 重新渲染，出现问题。
这是：[重现代码片段](https://developers.weixin.qq.com/s/7D3m3yme7jEy)

**Comment by MeFelixWang** [comment]
Your example works well without calling `reflow`, but bug does exist in `reflow`, I will find it out.

By the way, `setData` is async function, you should use callback if you want to do something after update data.
